from scripts.neon.table_to_class_name import table_to_class_name

PG_TO_PYTHON: dict[str, str] = {
    "uuid": "uuid.UUID",
    "text": "str",
    "character varying": "str",
    "varchar": "str",
    "char": "str",
    "boolean": "bool",
    "bool": "bool",
    "smallint": "int",
    "integer": "int",
    "bigint": "int",
    "real": "float",
    "double precision": "float",
    "numeric": "float",
    "timestamp without time zone": "datetime",
    "timestamp with time zone": "datetime",
    "timestamptz": "datetime",
    "date": "date",
    "time without time zone": "time",
    "time with time zone": "time",
    "json": "dict[str, Any]",
    "jsonb": "dict[str, Any]",
    "bytea": "bytes",
    # Postgres ENUMs surface as "USER-DEFINED" via information_schema.data_type. asyncpg returns them as plain strings, so the Python type is str.
    "USER-DEFINED": "str",
}

# Postgres array `udt_name` is `_<element-udt>` — strip the underscore and map.
_ARRAY_ELEMENT_MAP: dict[str, str] = {
    "text": "str",
    "varchar": "str",
    "bpchar": "str",
    "int2": "int",
    "int4": "int",
    "int8": "int",
    "bool": "bool",
    "float4": "float",
    "float8": "float",
    "uuid": "uuid.UUID",
}


def _py_type(pg_type: str, udt_name: str) -> str:
    if pg_type == "ARRAY":
        inner_udt = udt_name.lstrip("_")
        inner_py = _ARRAY_ELEMENT_MAP.get(inner_udt, "Any")
        return f"list[{inner_py}]"
    return PG_TO_PYTHON.get(pg_type, "Any")


def render_rows(schema: dict[str, list[tuple[str, str, str, bool]]]) -> str:
    """Render the schema into the source text for `app/services/neon/rows.py`.

    Computes the minimal set of imports the emitted file needs (`uuid`, `datetime`, `date`, `time`, `Any`) — anything unreferenced stays out so the generated file doesn't churn ruff warnings.
    """
    needs_uuid = False
    needs_datetime = False
    needs_date = False
    needs_time = False
    needs_any = False

    for cols in schema.values():
        for _name, pg_type, udt_name, _nullable in cols:
            py = _py_type(pg_type, udt_name)
            if "uuid.UUID" in py:
                needs_uuid = True
            if py == "datetime":
                needs_datetime = True
            elif py == "date":
                needs_date = True
            elif py == "time":
                needs_time = True
            if "Any" in py:
                needs_any = True

    lines: list[str] = [
        '"""TypedDicts mirroring the live Neon schema.',
        "",
        "Generated by ``scripts/neon/generate_neon_types.py`` — do not hand-edit.",
        "The pre-commit hook re-runs the generator and fails the commit if this file drifts.",
        '"""',
        "",
    ]
    if needs_uuid:
        lines.append("import uuid")
    datetime_imports: list[str] = []
    if needs_datetime:
        datetime_imports.append("datetime")
    if needs_date:
        datetime_imports.append("date")
    if needs_time:
        datetime_imports.append("time")
    if datetime_imports:
        lines.append(f"from datetime import {', '.join(datetime_imports)}")
    typing_imports = ["TypedDict"]
    if needs_any:
        typing_imports.insert(0, "Any")
    lines.append(f"from typing import {', '.join(typing_imports)}")
    lines.append("")

    for table in sorted(schema):
        cols = schema[table]
        class_name = table_to_class_name(table)
        lines.append("")
        lines.append(f"class {class_name}(TypedDict):")
        for col_name, pg_type, udt_name, nullable in cols:
            py = _py_type(pg_type, udt_name)
            if nullable:
                py = f"{py} | None"
            lines.append(f"    {col_name}: {py}")
    lines.append("")
    return "\n".join(lines)
