"""TypedDicts mirroring the live Neon schema.

Generated by ``scripts/generate_neon_types.py`` — do not hand-edit.
The pre-commit hook re-runs the generator and fails the commit if this file drifts.
"""

import uuid
from datetime import datetime
from typing import Any, TypedDict


class CalendarTokenRow(TypedDict):
    id: uuid.UUID
    user_id: uuid.UUID
    provider: str
    access_token: str
    refresh_token: str | None
    expires_at: datetime | None
    created_at: datetime
    updated_at: datetime


class ConversationSessionRow(TypedDict):
    id: uuid.UUID
    user_id: uuid.UUID
    persona_id: uuid.UUID | None
    started_at: datetime
    ended_at: datetime | None
    duration_seconds: int | None


class DeviceTokenRow(TypedDict):
    id: uuid.UUID
    user_id: uuid.UUID
    apns_token: str
    created_at: datetime


class EventRow(TypedDict):
    id: int
    user_id: uuid.UUID | None
    event_type: str
    ts: datetime
    props: dict[str, Any]


class MistakeRow(TypedDict):
    id: uuid.UUID
    user_id: uuid.UUID
    original: str
    corrected: str
    category: str
    count: int
    last_seen_at: datetime


class PersonaLikeRow(TypedDict):
    id: uuid.UUID
    user_id: uuid.UUID
    persona_id: uuid.UUID
    created_at: datetime


class PersonaRow(TypedDict):
    id: uuid.UUID
    name: str
    voice_id: str
    user_id: uuid.UUID
    created_at: datetime
    updated_at: datetime
    description: str
    role: str | None
    vocabulary_register: str | None
    conversational_style: str | None
    topical_preferences: str | None
    is_public: bool
    like_count: int
    age: str | None
    background: str | None


class PhraseFreqRow(TypedDict):
    user_id: uuid.UUID
    phrase: str
    count: int
    last_used_at: datetime


class TranscriptRow(TypedDict):
    session_id: uuid.UUID
    speaker: str
    text: str
    started_at: datetime
    ended_at: datetime
    id: int


class UserRow(TypedDict):
    id: uuid.UUID
    clerk_user_id: str
    email: str | None
    premium: bool
    premium_ends_at: datetime | None
    created_at: datetime
    updated_at: datetime
    display_name: str | None
    native_language: str | None
    target_accent: str | None
    goals: str | None
    location_city: str | None
    timezone: str | None
    personalization_consent: datetime | None
    product_improvement_consent: datetime | None
    consent_screen_seen_at: datetime | None
    name_pronunciation: str | None


class WordFreqRow(TypedDict):
    user_id: uuid.UUID
    lemma: str
    count: int
    last_used_at: datetime
