# /// script
# requires-python = ">=3.12"
# ///
"""Codegen TypeScript constants for the website from `app/iap/subscriptions_list.py`.

Output: `website/src/constants/iap-subscriptions.ts`. The website's Stripe checkout reads only what's emitted here — never hand-edits the file. Run from `boot.sh` so a `subscriptions_list.py` change reaches the website automatically before the next deploy.

Emits both sandbox and live Stripe price ids. The web checkout picks the right one based on `NODE_ENV` / Vercel env.

Run: `cd backend && uv run scripts/iap/generate_ts_constants.py`
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from app.iap.subscriptions_list import SUBSCRIPTIONS  # noqa: E402

OUT_PATH = (
    Path(__file__).resolve().parents[3] / "website" / "src" / "constants" / "iap-subscriptions.ts"
)


def main() -> None:
    rows: list[str] = []
    for s in SUBSCRIPTIONS:
        rows.append(
            "  {\n"
            f'    tier: "{s.tier.lower()}",\n'
            f'    cycle: "{s.cycle.lower()}",\n'
            f'    appleProductId: "{s.product_id}",\n'
            f'    targetUsdPrice: "{s.target_usd_price}",\n'
            f'    stripePriceSandbox: "{s.stripe_price.sandbox}",\n'
            f'    stripePriceLive: "{s.stripe_price.live}",\n'
            "  },"
        )
    rows_block = "\n".join(rows)
    tier_union = " | ".join(f'"{t}"' for t in sorted({s.tier.lower() for s in SUBSCRIPTIONS}))
    cycle_union = " | ".join(f'"{c}"' for c in sorted({s.cycle.lower() for s in SUBSCRIPTIONS}))

    ts = f"""// AUTO-GENERATED by backend/scripts/iap/generate_ts_constants.py
// Source of truth: backend/app/iap/subscriptions_list.py
// DO NOT EDIT BY HAND — regenerate via boot.sh or `uv run scripts/iap/generate_ts_constants.py`.

export type SubscriptionTier = {tier_union};
export type SubscriptionCycle = {cycle_union};

export type Subscription = {{
  tier: SubscriptionTier;
  cycle: SubscriptionCycle;
  appleProductId: string;
  targetUsdPrice: string;
  stripePriceSandbox: string;
  stripePriceLive: string;
}};

export const SUBSCRIPTIONS: readonly Subscription[] = [
{rows_block}
] as const;

/** Returns the right Stripe price id for the active deploy. APP_ENV / Vercel `NODE_ENV` decides. */
export function stripePriceFor(
  tier: SubscriptionTier,
  cycle: SubscriptionCycle,
): string {{
  const p = SUBSCRIPTIONS.find(
    (x) => x.tier === tier && x.cycle === cycle,
  );
  if (!p) throw new Error(`Unknown subscription: ${{tier}} ${{cycle}}`);
  const env = process.env.APP_ENV ?? process.env.NODE_ENV ?? "development";
  return env === "production" ? p.stripePriceLive : p.stripePriceSandbox;
}}
"""
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(ts)
    print(f"[ts-codegen] wrote {OUT_PATH.relative_to(OUT_PATH.parents[4])}")


if __name__ == "__main__":
    main()
