# /// script
# requires-python = ">=3.12"
# ///
"""Codegen Swift constants for iOS from `app/iap/subscriptions_list.py`.

Output: `ios/PalkieTalkie/Network/Subscription/Subscriptions.swift`. The iOS app reads only what's emitted here — never hand-edits the file. Run from `boot.sh` so a `subscriptions_list.py` change reaches iOS automatically before the next xcodegen+build.

Generated header tags the file as auto-generated so engineers don't try to maintain it by hand.

Run: `cd backend && uv run scripts/iap/generate_swift_constants.py`
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from app.iap.subscriptions_list import SUBSCRIPTIONS  # noqa: E402

OUT_PATH = (
    Path(__file__).resolve().parents[3]
    / "ios"
    / "PalkieTalkie"
    / "Network"
    / "Subscription"
    / "Subscriptions.swift"
)


def main() -> None:
    tiers = sorted({s.tier for s in SUBSCRIPTIONS})
    cycles = sorted({s.cycle for s in SUBSCRIPTIONS})

    tier_cases = "\n".join(f"    case {t.lower()}" for t in tiers)
    cycle_cases = "\n".join(f"    case {c.lower()}" for c in cycles)
    subscription_rows = "\n".join(
        f"        SubscriptionID(tier: .{s.tier.lower()}, cycle: .{s.cycle.lower()}),"
        for s in SUBSCRIPTIONS
    )

    swift = f"""// AUTO-GENERATED by backend/scripts/iap/generate_swift_constants.py
// Source of truth: backend/app/iap/subscriptions_list.py
// DO NOT EDIT BY HAND — regenerate via boot.sh or `uv run scripts/iap/generate_swift_constants.py`.

import Foundation

enum SubscriptionTier: String, CaseIterable, Identifiable {{
{tier_cases}

    var id: String {{
        rawValue
    }}
}}

enum SubscriptionCycle: String, CaseIterable, Identifiable {{
{cycle_cases}

    var id: String {{
        rawValue
    }}
}}

struct SubscriptionID: Hashable, Identifiable {{
    let tier: SubscriptionTier
    let cycle: SubscriptionCycle

    var rawValue: String {{
        "com.palkietalkie.\\(tier.rawValue).\\(cycle.rawValue)"
    }}

    var id: String {{
        rawValue
    }}

    static let all: [SubscriptionID] = [
{subscription_rows}
    ]

    static let allRawIDs: Set<String> = Set(all.map(\\.rawValue))

    init(tier: SubscriptionTier, cycle: SubscriptionCycle) {{
        self.tier = tier
        self.cycle = cycle
    }}

    init?(rawValue: String) {{
        let parts = rawValue.split(separator: ".")
        guard parts.count == 4,
              parts[0] == "com",
              parts[1] == "palkietalkie",
              let tier = SubscriptionTier(rawValue: String(parts[2])),
              let cycle = SubscriptionCycle(rawValue: String(parts[3]))
        else {{ return nil }}
        self.tier = tier
        self.cycle = cycle
    }}
}}
"""
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(swift)
    print(f"[swift-codegen] wrote {OUT_PATH.relative_to(OUT_PATH.parents[4])}")


if __name__ == "__main__":
    main()
